In [2]:
# Importing the libraries
from PIL import Image
from keras.applications.vgg16 import preprocess_input
import base64
from io import BytesIO
import json
import random
import cv2
from keras.models import load_model
import numpy as np

C:\Users\Surya\Anaconda3\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.


In [3]:
from keras.preprocessing import image
model = load_model('facefeatures_new_model.h5')

In [4]:
# Loading the cascades
face_cascade = cv2.CascadeClassifier('haarcascade_frontalface_default.xml')

In [5]:
def face_extractor(img):
    # Function detects faces and returns the cropped face
    # If no face detected, it returns the input image
    
    #gray = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
    faces = face_cascade.detectMultiScale(img, 1.3, 5)
    
    if faces is ():
        return None
    
    # Crop all faces found
    for (x,y,w,h) in faces:
        cv2.rectangle(img,(x,y),(x+w,y+h),(0,255,255),2)
        cropped_face = img[y:y+h, x:x+w]

    return cropped_face

In [6]:
# Doing some Face Recognition with the webcam
video_capture = cv2.VideoCapture(0)
while True:
    _, frame = video_capture.read()
    #canvas = detect(gray, frame)
    #image, face =face_detector(frame)
    
    face=face_extractor(frame)
    if type(face) is np.ndarray:
        face = cv2.resize(face, (224, 224))
        im = Image.fromarray(face, 'RGB')
           #Resizing into 128x128 because we trained the model with this image size.
        img_array = np.array(im)
                    #Our keras model used a 4D tensor, (images x height x width x channel)
                    #So changing dimension 128x128x3 into 1x128x128x3 
        img_array = np.expand_dims(img_array, axis=0)
        pred = model.predict(img_array)
        print(pred)
                     
        name="None matching"
        
        if(pred[0][1]>0.5):
            name='No mask found'
        cv2.putText(frame,name, (50, 50), cv2.FONT_HERSHEY_COMPLEX, 1, (0,255,0), 2)
    else:
        cv2.putText(frame,"Mask found", (50, 50), cv2.FONT_HERSHEY_COMPLEX, 1, (0,255,0), 2)
    cv2.imshow('Video', frame)
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break
video_capture.release()
cv2.destroyAllWindows()

[[6.257718e-32 1.000000e+00]]
[[5.6092136e-16 1.0000000e+00]]
[[0. 1.]]
[[3.7459963e-35 1.0000000e+00]]
[[1.3798478e-20 1.0000000e+00]]
[[2.2980566e-26 1.0000000e+00]]
[[0. 1.]]
[[0. 1.]]
[[0. 1.]]
[[2.9068306e-28 1.0000000e+00]]
[[0. 1.]]
[[0. 1.]]
[[0. 1.]]
[[0. 1.]]
[[1.0249055e-31 1.0000000e+00]]
[[8.296792e-35 1.000000e+00]]
[[8.63681e-21 1.00000e+00]]
[[0. 1.]]
[[0. 1.]]
[[0. 1.]]
[[4.6521505e-32 1.0000000e+00]]
[[0. 1.]]
[[0. 1.]]
[[0. 1.]]
[[0. 1.]]
[[1.0358788e-33 1.0000000e+00]]
[[0. 1.]]
[[2.7447747e-26 1.0000000e+00]]
[[0. 1.]]
[[0. 1.]]
[[1.28338e-21 1.00000e+00]]
[[5.567375e-05 9.999443e-01]]
[[1.0000000e+00 1.5723037e-14]]
[[6.662958e-17 1.000000e+00]]
[[5.1612112e-36 1.0000000e+00]]
[[0. 1.]]
[[6.515783e-34 1.000000e+00]]
[[0. 1.]]
[[0. 1.]]
[[0. 1.]]
[[0. 1.]]
[[8.672508e-19 1.000000e+00]]
[[7.2411597e-09 1.0000000e+00]]
[[0. 1.]]
[[0. 1.]]
[[0. 1.]]
[[1.3922876e-37 1.0000000e+00]]
[[0. 1.]]
[[1.0635211e-21 1.0000000e+00]]
[[0. 1.]]
[[0. 1.]]
[[0. 1.]]
[[0. 1.]]
[[4.70

[[0. 1.]]
[[2.0268142e-18 1.0000000e+00]]
[[0. 1.]]
[[0. 1.]]
[[1.9475621e-26 1.0000000e+00]]
[[0. 1.]]
[[0. 1.]]
[[0. 1.]]
[[0. 1.]]
[[0. 1.]]
[[1.674552e-36 1.000000e+00]]
[[2.5655673e-17 1.0000000e+00]]
[[0.00208991 0.9979101 ]]
[[9.9999976e-01 2.3168269e-07]]
[[3.415694e-14 1.000000e+00]]
[[6.84959e-26 1.00000e+00]]
[[2.1175514e-05 9.9997878e-01]]
[[1.8775304e-26 1.0000000e+00]]
[[0. 1.]]
[[4.114867e-33 1.000000e+00]]
[[0.5086497  0.49135035]]
[[5.9353017e-08 1.0000000e+00]]
[[1.8660821e-21 1.0000000e+00]]
[[2.6400607e-12 1.0000000e+00]]
[[9.9999988e-01 1.2616833e-07]]
[[0. 1.]]
[[5.5619215e-35 1.0000000e+00]]
[[0. 1.]]
[[1.5159836e-09 1.0000000e+00]]
[[3.1212625e-05 9.9996877e-01]]
[[1.1939747e-38 1.0000000e+00]]
[[2.2330403e-22 1.0000000e+00]]
[[1.9048196e-28 1.0000000e+00]]
[[3.5725414e-15 1.0000000e+00]]
[[1.000000e+00 8.678418e-11]]
[[1.0430322e-10 1.0000000e+00]]
[[1.0000000e+00 1.1733564e-11]]
[[7.9388e-30 1.0000e+00]]
[[7.0746254e-26 1.0000000e+00]]
[[0. 1.]]
[[1.0668151e-3

[[0.56854916 0.43145084]]
[[9.9997365e-01 2.6383595e-05]]
[[9.999007e-01 9.931871e-05]]
[[1.000000e+00 9.958017e-30]]
[[1.0000000e+00 2.9122952e-33]]
[[1.0000000e+00 1.0007149e-20]]
[[1.0000000e+00 2.7108989e-11]]
[[1.0000000e+00 1.8984488e-11]]
[[6.894051e-06 9.999931e-01]]
[[9.9999881e-01 1.1415083e-06]]
[[0.81940967 0.18059035]]
[[0.74526083 0.25473922]]
[[9.9988925e-01 1.1076549e-04]]
[[1.000000e+00 5.627577e-10]]
[[0.6592869  0.34071305]]
[[9.996314e-01 3.686058e-04]]
[[1.0000000e+00 5.6918796e-11]]
[[1.0000000e+00 1.2250882e-18]]
[[0.78883857 0.21116142]]
[[1.4281998e-15 1.0000000e+00]]
[[0.26009926 0.7399007 ]]
[[1.0000000e+00 2.3121257e-11]]
[[1.0000000e+00 2.7486249e-15]]
[[8.6084590e-05 9.9991393e-01]]
[[1.0000000e+00 3.3689928e-17]]
[[1.000000e+00 2.678966e-24]]
[[1.000000e+00 1.999363e-16]]
[[1.0000000e+00 2.6671498e-15]]
[[5.639251e-07 9.999994e-01]]
[[1.0000000e+00 6.0352287e-25]]
[[1.000000e+00 6.100537e-29]]
[[1.000000e+00 1.375623e-19]]
[[1. 0.]]
[[1. 0.]]
[[1.0000000e

KeyboardInterrupt: 